### ISSUE TITLE
Complete "arrived" structure for COMs (Master issue)

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/pocom#29]
From @joshbotts May 16, 2019 email:

> Bill approved adding initial arrival-to-post dates for COMs going forward. As a placeholder pending actual implementation of this change in the back-end, I’ve begun adding `<arrival><date></date><note></note></arrival>` between `<appointed>` and `<started>` in new `<chief>` elements. I also added an “Arrived” item to `role-chief-event-codes` (and tweaked the description for “Credentialed”). We still need to finalize the explanatory text that will be added to the POCOM landing page for this addition to new and future COM entries.

The item in `code-tables/role-chief-event-codes.xml`:

```xml
<item>
    <label>Arrived</label>
    <value>arrived</value>
    <class>chief</class>
    <definition>The date a person arrived and assumed charge of a diplomatic post.</definition>
</item>
```

On June 3, 2019, @joshbotts submitted a PR updating arrival dates to all new COMs - https://github.com/HistoryAtState/pocom/pull/19 - noting:

> New COMs had added `<arrived>` element noting when they assumed charge over mission (this usually coincided with their arrival at post). CDA and CDAai COMs do not have `<arrived>` data.

Definitions from Draft DOA Documentation:

> Assumption of Charge Date: If the date is not known authoritatively, then this field should be left blank. Once implemented on the website, the full date will appear after “Assumed Charge:” within ordered list item associated with position on the webpage associated with the incumbent. Year is listed as first value within parenthetical date range following the name of the incumbent on the webpage associated with the Contemporary Territory ID.
> 
> Assumption of Charge Note: Once implemented on the website, would be inserted between “Assumed Charge: ” and the assumption of charge date on website.

Tasks to complete integration:

- [x] Add `<arrived>` structure to our schema for COM data
- [x] Add `<arrived>` structure to records missing it
- [x] Implement handling for display of arrived date and note in all POCOM views on hsg-shell
- [x] Add explanatory text to the ["Dates of Service"](https://history.state.gov/departmenthistory/people/principals-chiefs#dates-of-service) section of [the HTML template](https://github.com/HistoryAtState/hsg-shell/blob/master/pages/departmenthistory/people/principals-chiefs.xml) on the POCOM landing page

**Comment by joshbotts** [comment]
Hi @joewiz - this looks good to me. 

With regards to the new language for the "Dates of Service" section, here's the change that the DID team proposed in 2019:

Replace the text “Chiefs of Mission are considered to have entered on duty when they present their credentials to their host governments.” with “Upon assuming charge of their mission, Chiefs of Mission possess the authority and responsibility to manage their post and oversee the conduct of its operations. Upon presenting their credentials to the host government, Chiefs of Mission are recognized as the principal diplomatic representative of the United States Government. Both assumption of charge over the U.S. mission and presentation of credentials to the host government are important elements of a chief of mission’s entrance on duty.”

**Comment by joewiz** [comment]
All tasks are complete. 

Thanks, @joshbotts!
